.\" ************************************************************
.\"
.\" name sect foot-centre foot-left  head-centre   origin  architecture
.TH yfd  8  "22 Mar 2025"  "oz-sheets"  "yfd"
.SH NAME
.BR yfd " \- expose Yahoo Finance data via a simple JSON API."
.SH SYNOPSIS
.TP
yfd [\-p nnn] [\-h] [\-v]
.SH OPTIONS
.LP
.TP 4
\fB\-h\fP (\fB\-\-help\fP)
Prints a brief usage message containing legal syntax and functions and
exits.
.TP 4
\fB\-p\fP n
Specify a TCP port number on which to listen for HTTP connections.
The default is 8000.
.TP 4
\fB\-v\fP (\fB\-\-version\fP)
Prints the version number.
.SH DESCRIPTION
.LP
The \fByfd\fP daemon exports an HTTP endpoint through which clients can
request data from the Yahoo Finance website in JSON format.
.LP
The daemon is intended for use with
.BR systemd (8)
and consequently does not support daemonisation or
.BR syslog (3)
output, relying on a systemd unit to run as a service.
.LP
.B yfd
should not be deployed directly in production, but should use a
web-facing proxy such as
.BR nginx .
.LP
.SH EXIT CODES
.PP
.TP 8
0
Suceeded.
.TP 8
1
Error.
.LP
.SH "SEE ALSO"
.LP
.BR nginx (8),
.BR systemd (8),
.LP
.B https://finance.yahoo.com
.SH SOURCE
.LP
.B https://github.com/billsegall/oz-sheets
.SH AUTHORS
.LP
David Arnold (d@0x1.org) and Bill Segall (bill@segall.net)
